apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kubernetes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gugo1943exsi/test.git
    targetRevision: main
    path: SlutProdukt
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true