apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webserver2
  template:
    metadata:
      labels:
        app: my-webserver2
    spec:
      containers:
      - name: my-webserver2
        image: ghcr.io/gugo1943exsi/hello-gig:latest
        imagePullPolicy: Always
